### ISSUE TITLE
My Serial number

### ISSUE THREAD

**Issue by rubinholima** [mightythemes/Mighty-Addons#6]
Hello,

How can i deactivate the Mighty theme from one site to another, and where i find my serial number to setup in the right one?

**Comment by actuallyakash** [comment]
Hey @rubinholima 

Thank you for using Mighty Addons.

You can find and manage all the keys & sites from the [dashboard](https://mightythemes.com/dashboard/) by clicking **Manage Sites**.

Let me know if you've any other questions.

Thanks.

**Comment by rubinholima** [comment]
This option is gray and not open anything..

**Comment by actuallyakash** [comment]
Hey @rubinholima 

This was fixed previously and forgot to update here. It was fixed.
